# Generated by Django 4.2.3 on 2024-01-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default='True'),
        ),
    ]
