# Generated by Django 4.2.3 on 2024-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
